package nodamushi.hl.analysis.parser;

import java.util.Collection;

import nodamushi.hl.analysis.Token;
import nodamushi.hl.analysis.TokenTypePreDefine;

/**
 * JFlex等で作ったパーサーが実装するべきメソッドを定義したインターフェース。<br>
 * インターフェースでは定義できなかったが、コンストラクタが文字列を受け取ることが出来ることが好ましい。
 * @author nodamushi
 *
 */
public interface AutoGeneratedParser extends TokenTypePreDefine{
    /**
     * パース処理
     * @return
     */
    Collection<Token> parse();
}
