package nodamushi.hl.analysis.parser;

import java.util.Collection;

import nodamushi.hl.analysis.Token;
import nodamushi.hl.analysis.TokenTypePreDefine;

/**
 * FlexParsrで使用するJFlexで作ったパーサーが実装しなくてはならないインターフェース。<br>
 * インターフェースでは定義できなかったが、コンストラクタが文字列を受け取るようにする。
 * @author nodamushi
 *
 */
public interface AutoGeneratedParser extends TokenTypePreDefine{
    /**
     * パース処理
     * @return Tokenのコレクション。このコレクションが空の時、処理が終わった物と見なす。
     * <br>コレクションの中身はFlexParserにより受け取った後に空にされる。
     */
    Collection<Token> parse();
}
