package nodamushi.hl.analysis.parser;

import nodamushi.hl.analysis.parser.flex.JavaScriptFlexParser;

public class JavaScriptParser extends FlexParser{
    
    @Override
    public String language(){
        return "javascript";
    }
    

    @Override
    protected AutoGeneratedParser createParser(String source){
        return new JavaScriptFlexParser(source);
    }

    @Override
    protected String defaultKeywordDefine(){
        return T.keywordDefine;
    }
    
    
    //ダブルチェックロッキングパターンの代わり
    private static class T{
        static final String keywordDefine;
        static{
            keywordDefine = readPackageTextFile("javascriptparser.txt");
        }
    }
}
