package nodamushi.hl.analysis.parser;

import nodamushi.hl.analysis.parser.flex.TextFlexParser;
public class TextParser extends FlexParser{

    @Override
    public String language(){
        return "text";
    }
    
    @Override
    protected AutoGeneratedParser createParser(String source){
        return new TextFlexParser(source);
    }
}
