package nodamushi.hl.analysis.parser;

import nodamushi.hl.analysis.parser.flex.TextFlexParser;

public class TextParser extends FlexParser{

    @Override
    protected AutoGeneratedParser createParser(String source){
        return new TextFlexParser(source);
    }
}
