package nodamushi.hl.html;

import nodamushi.hl.analysis.Token;
import nodamushi.hl.analysis.parser.AutoGeneratedParser;
import nodamushi.hl.analysis.parser.FlexParser;

class HTMLTemplateParser extends FlexParser{
    
    @Override
    public String language(){
        return "htmltemplate";
    }
    
    
    public HTMLTemplateParser(){
        super();
        ignore_newline=true;
    }
    @Override
    protected AutoGeneratedParser createParser(String source){
        return new HTMLTemplateFlexParser(source);
    }
    
    @Override
    protected void appendParsedToken(Token t){
        if(t.getType()!=PLAIN_TOKEN||t.getType()!=COMMENT_TOKEN)
            super.appendParsedToken(t);
    }

}
